### ISSUE TITLE
Feature | Build Leverage CLI images for `amd64` and `arm` architectures

### ISSUE THREAD

**Issue by angelofenoglio** [binbashar/le-dev-makefiles#28]
## Describe the Feature

Add targets to allow the docker images used by Leverage CLI to be built not only for `amd64` architecture, but also `arm` in it's multiple versions.

## Rationale

M1 Mac users experience an extremely slow execution of the cli commands due to the docker image not being built for that platform. This enhancement would bring a big qol improvement for these user as well as cover other `arm` platforms.

**Comment by angelofenoglio** [comment]
CC: @diego-ojeda-binbash @exequielrafaela @lgallard

**Comment by exequielrafaela** [comment]
@angelofenoglio hi! Thanks for creating this issue 🙏🏼 
I'll give it a try and let you know how it goes. I couldn't find the time today, but I'll doit ASAP 💪🏼 

```
docker buildx build \
--platform linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7,linux/arm/v8 \
--push \
-t binbash/terraform-awscli-slim:1.1.3 \
--build-arg DOCKER_TAG=1.1.3 .
```
